version: '3.8'

services:
  app-backend:
    container_name: appbackend
    build: ./app-backend
    depends_on:
      - postgres
      - monitor
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mydb
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=mypassword
    ports:
      - "8080:8080"
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "5432:5432"
  app-frontend:
    build: ./app-frontend
    depends_on:
      - postgres
      - app-backend
    ports:
      - "80:80"
  monitor:
    container_name: monitor
    build: ./monitor
    ports:
      - "9090:9090"

